version: "3.4"
services:
  nginx:
    image: nginx
    network_mode: "host"
    container_name: nginx
    restart: on-failure
    volumes:
      - ./files:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/nginx.conf